### ISSUE TITLE
Cannot build - missing symbol org.dcm4che3.imageio.stream.RAFFileImageInputStream

### ISSUE THREAD

**Issue by acaland** [wayfarer3130/static-wado#5]
Hello,

I am not able to build the project as it's missing a dependency. I have checked the `org.dcm4che3.imageio` source in its repo and this class is missing. What am I doing wrong?

thanks

```
> Task :StudyManager:compileJava FAILED
/private/tmp/static-wado/StudyManager/src/main/java/org/dcm4che/staticwado/StudyManager.java:20: error: cannot find symbol
import org.dcm4che3.imageio.stream.RAFFileImageInputStream;
                                  ^
  symbol:   class RAFFileImageInputStream
  location: package org.dcm4che3.imageio.stream
/private/tmp/static-wado/StudyManager/src/main/java/org/dcm4che/staticwado/StudyManager.java:173: error: cannot find symbol
      try (FileImageInputStream fiis = new RAFFileImageInputStream(file)) {
                                           ^
  symbol:   class RAFFileImageInputStream
  location: class StudyManager
2 errors
```

**Comment by wayfarer3130** [comment]
You arent doing anything wrong - I made a fix to dcm4che which hasn't
gotten integrated yet.  Removed that dependency, you should be able to pull
from:

**Comment by wayfarer3130** [comment]
Sorry, sent automatically on paste, pull from:
 https://github.com/OHIF/static-wado.git

This version has temporarily removed some functionality around converting
image types, as I re-wrote the control flow quite a bit to make it thread
safe in a multi system environment.

Bill.

**Comment by acaland** [comment]
Thank you. Now I am able to build
When I tried to run the first time StaticWado bin reported it cannot find the  OpenCV java library, even if I set the environment variables as described in the readme. So I just copied the `libopencv_java.jnilib` into my `~/Library/Java/Extensions/` (I am on a Mac) and it worked.

However the generated static assets from a dicom study are garbage:


![image](https://user-images.githubusercontent.com/3988594/148444747-6b92be28-966c-48e4-b8e2-2f97e84b8c18.png)


Do you have any idea of what could be the cause?

please find below the output from the run of staticWado:

```
% ./bin/StaticWado ~/Downloads/DICOM/     
[main] WARN org.dcm4che.staticwado.StudyManager - Import dicom dir /Users/acaland/Downloads/DICOM name 00000034
[main] WARN org.dcm4che.staticwado.CompleteStudyHandler - createStudy Data 114368.13103.356210670.37767097802.16886754.744844577
[main] WARN org.dcm4che.staticwado.StudyData - Reading 0 deduplicated files
[main] WARN org.dcm4che.staticwado.StudyData - Reading 0 deduplicated files
[main] WARN org.dcm4che.staticwado.ExtractImageFrames - sourceTsuid = 1.2.840.10008.1.2.4.70
gen 06, 2022 8:59:24 PM org.opencv.osgi.OpenCVNativeLoader init
INFORMAZIONI: Successfully loaded OpenCV native library.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dcm4che3.opencv.StreamSegment (file:/private/tmp/static-wado/StaticWado/build/install/StaticWado/lib/dcm4che-imageio-opencv-5.25.1.jar) to field javax.imageio.stream.FileImageInputStream.raf
WARNING: Please consider reporting this to the maintainers of org.dcm4che3.opencv.StreamSegment
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] WARN org.dcm4che.staticwado.InstanceDeduplicate - source for deduplicate available tsuid 1.2.840.10008.1.2.4.70
[main] WARN org.dcm4che.staticwado.InstanceDeduplicate - destination for deduplicate available tsuid null
[main] WARN org.dcm4che.staticwado.StudyManager - Import dicom dir /Users/acaland/Downloads/DICOM name 00000033
[main] WARN org.dcm4che.staticwado.ExtractImageFrames - sourceTsuid = 1.2.840.10008.1.2.4.70
...
```

thank you

**Comment by wayfarer3130** [comment]
Is that a current version of OHIF - there were a couple of fixes to allow
decoding other image formats in both OHIF v2 and v3.  It looks to me like
the data you are getting back is ok, and is compressed data, but isn't
getting decompressed as expected.  Try a simple CR or CT image first - the
cancer imaging archive has a good set of data.  Otherwise, I would need to
look at the DICOM header to figure out what is going on, but I do know
there are still incompatibilities depending on the data types where OHIF
doesn't deal with data - particularly colour data.

I would also take a look in the frames data - it isn't hard to extract the
raw pixels to compare them with what is in the DICOM file.

There is also a javascript version of this dicomp10-to-dicomweb available
on github that does less processing than this version, but I know that
there are still colour incompatibilities there, which I think are in OHIF,
but I haven't dug down yet.

**Comment by acaland** [comment]
I tried both the v3-stable viewer and the one from master (v4) both with the same behaviour.
I tried dicomp10-to-dicomweb and this one convert the files correctly.

I could send via e-mail one of the DICOM file I am using if you have time to have a look to it.

**Comment by wayfarer3130** [comment]
You should send directly to my email: ***@***.*** and I will
take a look.  I wrote the code in dicomp10-to-dicomweb as well, so I might
just look at the headers and not do any image conversion for that type of
image, but I'd like to see what they are first.

Bill

**Comment by acaland** [comment]
With the latest commit now the images are loaded correctly. Thank you
